### ISSUE TITLE
Question about localization of plugin

### ISSUE THREAD

**Issue by brrttwrks** [babolivier/collateral-freedom#1]
We are working with RSF and I have a question: is it possible to localize the plugin? Ideas how I can help localize the plugin into the Azeri language?

**Comment by babolivier** [comment]
Hi @brrttwrks,

Very sorry about the delay, been quite busy lately (and still am).

Right now it's not possible to localize the plugin, however it's be a nice feature and not too difficult to implement (in my opinion). I'll see if I get the time to work on that, but can't make any promise in the close future. If anyone's interested in coding this, please get in touch, I'd be happy to help.

**Comment by limpapud** [comment]
Well, is it possible now?

**Comment by babolivier** [comment]
Hi @brrttwrks & @limpapud!

I'm so sorry about the time it took me to process this (I've been rather busy in my personal life). The extension is [now fully internationalised](https://github.com/babolivier/collateral-freedom/releases/tag/1.3)!

Please open a pull request with the strings from the language(s) you'd like to add, or give them to me in a separate issue so I can add them. Either ways, I'll merge it in both the FF and Chrome version and release a new update.

Thanks for your interest in this work and for your patience, and again, sorry for the delay!
